# Generated by Django 6.0.5 on 2026-05-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_ejercicio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futbolista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100, null=True)),
                ('genero', models.CharField(max_length=100)),
                ('ciudad_residencia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=150)),
                ('especialidad', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('salario_basico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('programado', models.BooleanField(default=True)),
            ],
        ),
    ]
