# Generated by Django 6.0.5 on 2026-06-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_ejercicio_app', '0002_futbolista_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=10, unique=True)),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('habitantes', models.PositiveIntegerField()),
                ('num_vecionos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Alcalde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_ejercicio_app.municipio')),
            ],
        ),
    ]
