# Generated by Django 6.0.5 on 2026-06-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_ejercicio_app', '0003_municipio_alcalde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='num_vecionos',
            new_name='municipio_vencino',
        ),
        migrations.CreateModel(
            name='Vereda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mi_ejercicio_app.municipio')),
            ],
        ),
    ]
