# Generated by Django 6.0.5 on 2026-06-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_ejercicio_app', '0004_rename_num_vecionos_municipio_municipio_vencino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcalde',
            name='tipo_doc',
            field=models.CharField(default='C.C', max_length=5),
        ),
        migrations.AlterField(
            model_name='alcalde',
            name='municipio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi_ejercicio_app.municipio'),
        ),
    ]
